[package]
name = "ruffle_web_common"
version.workspace = true
authors = ["Ruffle LLC <ruffle@ruffle.rs>"]
edition.workspace = true
license = "MIT OR Apache-2.0"

[lints]
workspace = true

[dependencies]
tracing = { workspace = true }
wasm-bindgen = { workspace = true }
